### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by frantisekhanzlikbl** [mkaito/nixos-modded-minecraft-servers#2]
Hey, this is not really an issue, but I just wanted to thank you for this module, it's saved me a lot of work. :smiley: 
Tour other public nix files have also been really useful for figuring some stuff out.

Feel free to close this whenever, and thanks again for publishing your work!

PS: I am still conflicted about whether the `authorized_keys` rsync trick is absolutely genius or horribly evil :smile:

**Comment by mkaito** [comment]
Hey, thank you very much for the kind words. I really appreciate it! And I'm glad you found this useful. Have a great day!
